# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad615bad44c8e75ce911a768278d594aa38f879d5e7b02c207cbfb0db7aa7229b79aec33879c8637e689fc9bc3d08beadaafc0a658b191a25af4aa26854e776

test:
  secret_key_base: 61a6c14b7bfca4a2a4182e7069532be2fef1570546413b4838f86ea878282b187884b2c0beddb45afc57340edbaf9c4eaa3b599af03057f1d44b3fcac234e663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
